name: CostAnalysis ETL Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Confirm scheduled trigger
        run: echo "Scheduled workflow triggered successfully"
